### ISSUE TITLE
Add mapping for properties (raw values for facets)

### ISSUE THREAD

**Issue by borsna** [NordicHealthData/search-portal#2] opened 2015-08-25 14:17 UTC
e.g. Subjects can contain spaces, we need to add a raw value in the mappings to be able to do aggregations on the full string.

https://www.elastic.co/guide/en/elasticsearch/guide/current/aggregations-and-analysis.html

**Comment by jvjensen** [comment] 2016-03-02 17:00
Duplicate of #31

**Closed as completed by jvjensen** 2016-03-02 17:00 UTC
Labels: enhancement, Elastic Search
